arch_config_timezone: Europe/Budapest
arch_config_locale: en_US.UTF-8
arch_config_user_name: changeme
arch_config_user_password: changeme
arch_config_user_groups: wheel
arch_config_user_shell: /bin/zsh
arch_config_hostname: lenovo
