- name: Dotfiles | Set up dotfiles
  block:
    - name: Dotfiles | Install git
      ansible.builtin.package:
        name: git

    - name: Make sure destination directory is empty
      ansible.builtin.file:
        path: /home/{{ arch_config_user_name }}
        state: "{{ item }}"
      loop:
        - absent
        - directory

    - name: Dotfiles | Clone the specified dotfile repository
      ansible.builtin.git:
        repo: "{{ arch_config_dotfile_repo }}"
        dest: "/home/{{ arch_config_user_name }}"
        refspec: +refs/heads/*:refs/remotes/origin/*
        separate_git_dir: "/home/{{ arch_config_user_name }}/.cfg"
  when: arch_config_dotfile_repo is defined
