- name: Misc | X11 Configure touchpad
  ansible.builtin.copy:
    content: |
      Section "InputClass"
          Identifier "touchpad"
          Driver "libinput"
          MatchIsTouchpad "on"
          Option "Tapping" "on"
          Option "NaturalScrolling" "true"
      EndSection
    dest: /etc/X11/xorg.conf.d/30-touchpad.conf
