# Does not work in chroot
# - name: Network configuration | Set the hostname
#   ansible.builtin.hostname:
#     name: "{{ arch_config_hostname }}"
#     use: systemd

- name: Network configuration | Set the hostname
  ansible.builtin.copy:
    content: "{{ arch_config_hostname }}"
    dest: /etc/hostname

- name: Network configuration | Enable networking services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: yes
  loop:
    - NetworkManager
    - systemd-resolved
    - ufw
