# Does not work in chroot
# - name: Network configuration | Set the hostname
#   ansible.builtin.hostname:
#     name: "{{ arch_config_hostname }}"
#     use: systemd

- name: Network configuration | Set the hostname
  ansible.builtin.copy:
    content: "{{ hostvars['localhost']['arch_config_hostname'] }}"
    dest: /etc/hostname
