- name: Packages | Install packages from standard repositories
  ansible.builtin.package:
    name: "{{ arch_config_standard_packages }}"

- name: Packages | Install python-pip
  ansible.builtin.package:
    name: python-pip

- name: Packages | Install packages from PyPi
  ansible.builtin.pip:
    name: "{{ arch_config_pip_packages }}"
