- name: Packages | Install packages from standard repositories
  ansible.builtin.package:
    name: "{{ arch_config_standard_packages }}"
  when: arch_config_standard_packages is defined and arch_config_standard_packages | length > 0
