- name: Packages | Install packages from standard repositories
  community.general.pacman:
    name: "{{ item.package | default(item) }}"
  loop: "{{ arch_config_standard_packages }}"
  when: arch_config_standard_packages is defined

- name: Packages | Install packages from PyPi
  ansible.builtin.pip:
    name: "{{ item.package }}"
  loop: "{{ arch_config_pip_packages }}"
  when: arch_config_pip_packages is defined
