- name: Shell configuration | Install dash
  ansible.builtin.package:
    name: dash

- name: Shell configuration | Create symlink /bin/sh -> dash
  ansible.builtin.file:
    src: dash
    dest: /usr/bin/sh
    state: link

- name: Shell configuration | Create pacman hook to relink /bin/sh after system updates
  ansible.builtin.copy:
    content: |
      [Trigger]
      Type = Package
      Operation = Install
      Operation = Upgrade
      Target = bash

      [Action]
      Description = Re-pointing /bin/sh symlink to dash...
      When = PostTransaction
      Exec = /usr/bin/ln -sfT dash /usr/bin/sh
      Depends = dash
    dest: /usr/share/libalpm/hooks/dashbinsh.hook

- name: Shell configuration | Create pacman hook to refresh zsh completions after installing a package
  ansible.builtin.copy:
    content: |
      [Trigger]
      Operation = Install
      Operation = Upgrade
      Operation = Remove
      Type = Path
      Target = usr/bin/*

      [Action]
      Depends = zsh
      Depends = procps-ng
      When = PostTransaction
      Exec = /usr/bin/pkill zsh --signal=USR1
    dest: /usr/share/libalpm/hooks/zsh-rehash.hook

- name: Shell configuration | Set zsh config directory
  ansible.builtin.copy:
    content: ZDOTDIR={{ arch_config_zdotdir }}
    dest: /etc/zsh/zshenv
